# Cell Therapy Analytics Pipeline Configuration
# Configuration file for bioinformatics data processing pipeline

# Pipeline Settings
pipeline:
  name: "Cell Therapy Analytics Pipeline"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  
# Data Processing Parameters
processing:
  # Flow Cytometry Analysis
  flow_cytometry:
    min_events: 10000  # Minimum events required for analysis
    max_events: 100000  # Maximum events to process
    gating_strategy: "automated"  # automated, manual, hybrid
    compensation_method: "auto"  # auto, manual, none
    
    # Cell Population Gates
    gates:
      live_cells:
        fsc_threshold: 50000
        ssc_threshold: 30000
        viability_marker: "PI"  # Propidium Iodide
        viability_threshold: 0.1
        
      t_cells:
        cd3_threshold: 1000
        cd4_threshold: 500
        cd8_threshold: 500
        
      nk_cells:
        cd56_threshold: 1000
        cd16_threshold: 500
        
      b_cells:
        cd19_threshold: 1000
        cd20_threshold: 500
    
    # Quality Control Parameters
    quality_control:
      min_viability: 70.0  # Minimum viability percentage
      max_viability: 100.0  # Maximum viability percentage
      outlier_threshold: 3.0  # Standard deviations for outlier detection
      batch_consistency_threshold: 0.85  # Minimum correlation between batches
      
  # Cell Counting Parameters
  cell_counting:
    min_cell_count: 1000
    max_cell_count: 10000000
    viability_threshold: 70.0
    density_calculation: true
    counting_methods: ["automated", "manual", "hemocytometer"]
    
  # Statistical Analysis
  statistics:
    confidence_level: 0.95
    sample_size_calculation: true
    power_analysis: true
    multiple_testing_correction: "bonferroni"  # bonferroni, fdr, none
    
# Validation Rules
validation:
  # Data Integrity Rules
  data_integrity:
    required_fields:
      - sample_id
      - batch_id
      - acquisition_date
      - technician_id
      
    data_types:
      sample_id: "string"
      batch_id: "string"
      acquisition_date: "datetime"
      total_events: "integer"
      viability_percentage: "float"
      
    value_ranges:
      total_events: [1000, 1000000]
      viability_percentage: [0.0, 100.0]
      cell_density: [0.0, 1000000.0]
      
  # Business Rules
  business_rules:
    # Sample Processing Rules
    sample_processing:
      max_processing_time_hours: 24
      required_metadata_fields: ["patient_id", "cell_type", "collection_date"]
      quality_score_threshold: 0.8
      
    # Batch Processing Rules
    batch_processing:
      max_batch_size: 100
      min_batch_size: 5
      batch_consistency_check: true
      cross_batch_validation: true
      
    # Change Control Rules
    change_control:
      require_approval: true
      approval_threshold: 2  # Number of approvals required
      change_logging: true
      rollback_enabled: true
      
# Performance Settings
performance:
  # Processing Optimization
  optimization:
    parallel_processing: true
    max_workers: 4
    chunk_size: 1000
    memory_limit_gb: 8
    
  # Caching
  caching:
    enable_cache: true
    cache_ttl_hours: 24
    cache_size_mb: 1000
    
  # Database
  database:
    connection_pool_size: 20
    max_overflow: 30
    pool_recycle_seconds: 3600
    query_timeout_seconds: 300
    
# Monitoring and Alerting
monitoring:
  # Metrics Collection
  metrics:
    collect_performance_metrics: true
    collect_quality_metrics: true
    collect_business_metrics: true
    
  # Alerting
  alerting:
    enable_alerts: true
    alert_channels: ["email", "slack", "dashboard"]
    
    thresholds:
      processing_time_minutes: 60
      error_rate_percentage: 5.0
      data_quality_score: 0.8
      system_uptime_percentage: 99.5
      
# Reporting
reporting:
  # Dashboard Configuration
  dashboard:
    refresh_interval_seconds: 300
    max_data_points: 1000
    export_formats: ["pdf", "excel", "csv"]
    
  # Report Generation
  reports:
    daily_summary: true
    weekly_analysis: true
    monthly_trends: true
    batch_completion: true
    
    templates:
      quality_report: "templates/quality_report.html"
      batch_summary: "templates/batch_summary.html"
      trend_analysis: "templates/trend_analysis.html"
      
# Security
security:
  # Authentication
  authentication:
    method: "ldap"  # ldap, oauth, basic
    session_timeout_minutes: 480
    max_login_attempts: 5
    
  # Data Protection
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    data_retention_days: 2555  # 7 years
    audit_logging: true
    
# Integration Settings
integration:
  # External Systems
  external_systems:
    lims_integration:
      enabled: true
      api_endpoint: "https://lims.company.com/api"
      sync_interval_minutes: 30
      
    eln_integration:
      enabled: true
      api_endpoint: "https://eln.company.com/api"
      sync_interval_minutes: 60
      
  # File Storage
  file_storage:
    raw_data_path: "./data/raw"
    processed_data_path: "./data/processed"
    backup_path: "./data/backup"
    archive_path: "./data/archive"
    
# Development Settings
development:
  # Debugging
  debugging:
    enable_debug_logging: true
    log_level: "INFO"
    profile_performance: false
    
  # Testing
  testing:
    test_data_path: "./tests/test_data"
    mock_external_services: true
    run_integration_tests: true
    
# Business Impact Metrics
business_metrics:
  # Performance Targets
  performance_targets:
    processing_time_reduction_percentage: 65
    data_integrity_compliance_percentage: 94
    quality_control_automation_percentage: 80
    change_control_efficiency_percentage: 100
    
  # Quality Metrics
  quality_metrics:
    min_viability_percentage: 85.0
    max_batch_variability_percentage: 15.0
    min_sample_quality_score: 0.8
    max_processing_error_rate: 2.0 